###
# Login to obtain status
POST http://localhost:5097/api/v1/Login/Login
Content-Type: application/json

{
  "username": "admin1",
  "password": "password"
}

###
# Check if admin is logged in
GET http://localhost:5097/api/v1/Login/IsAdminLoggedIn
Content-Type: application/json

###

# Logout
GET http://localhost:5097/api/v1/Login/Logout
Content-Type: application/json

###

# Get all reservations 
GET http://localhost:5097/api/v1/admin/reservations
Content-Type: application/json

###

# Get reservations for a specific show and date
GET http://localhost:5097/api/v1/admin/reservations?show=TheatreShowTitle&date=2024-10-16
Content-Type: application/json

###

# Search reservation by email
GET http://localhost:5097/api/v1/admin/reservations/search?email=customer@example.com
Content-Type: application/json

###

# Search reservation by reservation number
GET http://localhost:5097/api/v1/admin/reservations/search?reservationNumber=1234
Content-Type: application/json

###

# Mark a reservation as used
PATCH http://localhost:5097/api/v1/admin/reservations/1/mark-used
Content-Type: application/json

###

# Delete reservation
DELETE http://localhost:5097/api/v1/admin/reservations/1
Content-Type: application/json
